In [3]:
import numpy as np 
#! ndarrays are vectotrized arrays that work in parallel

## 1. Array Creation

In [6]:
# creating ndarrays 
Arr = np.array([1,2,3,4,5]) # 1D array
Arr2d = np.array([[1,2,3],[4,5,6]]) # 2D array

# u can ge tht dimensions of an array 
print(Arr.ndim)
print(Arr2d.ndim)
print(Arr2d.dtype)

1
2
int32


In [9]:
rand_arr = np.random.rand(3, 3)
ranged_arr = np.arange(0, 10, 2)

print(rand_arr)
print(ranged_arr)


[[0.41403187 0.17293234 0.94028437]
 [0.9534787  0.05104826 0.54900115]
 [0.43577051 0.37139303 0.9235625 ]]
[0 2 4 6 8]


## 2. Array Operations

In [12]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c = a + b #* it's performed elementwise
d = a - b
print(c)
print(d)
boolean_arr = a > 3
print(boolean_arr)
#* applying a function to an array
modified_arr = a[boolean_arr] 
print(modified_arr)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[False False False  True  True]
[4 5]


In [15]:
#* array dtype

#! numpy.dtype will choose the data type that fits all the elements in the array
array_1 = np.array([1.0,2,3,4,5])
print(array_1.dtype)
array_1 = np.array([1,2,3.0,4,5])
print(array_1.dtype)

float64
float64


### matrix multiplication

In [13]:
Mat_A = np.array([[1,2,3],[4,5,6],[7,8,9]])
Mat_B = np.array([[1,2,3],[4,5,6],[7,8,9]])

#* matrix multiplication
## using * operator will perform multiplication elementwise
## using @ operator will perform matrix multiplication

print(Mat_A * Mat_B)
print(Mat_A @ Mat_B)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [16]:
array_1 = np.array([1,2,3,4,5])
print(array_1.sum()) #* sum of all elements
print(array_1.mean()) #* average of all elements
print(array_1.std()) #* standard deviation of all elements
print(array_1.var()) #* variance of all elements
print(array_1.min()) #* minimum of all elements
print(array_1.max()) #* max and min are also functions
print(array_1.argmin()) #* returns the index of the minimum element
print(array_1.argmax()) #* returns the index of the maximum element

15
3.0
1.4142135623730951
2.0
1
5
0
4


In [ ]:
# from PIL import Image
# array = np.array(Image.open('/home/jatin/Downloads/python_logo.png'))
# #* converting an image to an ndarray

## 2. Indexing, Slicing, and Iterating

In [25]:
array_1 = np.array([1, 2, 3, 4, 5])
array_1[4]  # * indexing

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d[1])
print(array_2d[1][1])
print(array_2d[1, 1])

print(array_1[array_1 > 3])  # * returns the elements greater than 3


[4 5 6]
5
5
[4 5]


In [27]:
#! slicing
print(array_2d[2:])
print(array_2d[:2])
print(array_2d[1:3])
print(array_2d[1:3, 1:3])


[[7 8 9]]
[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]


In [ ]:
# rading from a file
#! might want to check the genfromtxt function later
Iris = np.genfromtxt('iris.csv', delimiter=',', dtype=None)
Iris[:, 0]  # * will return the first column as a single list
Iris[:, 0:1]  # * this will preserve the dimension of the columns
Iris[:, 0]  # * will return the first column as a single list
Iris[:, 0:1]  # * this will preserve the dimension of the columns


## np.reshape(array, shape)

In [ ]:
import numpy as np

def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 


a = np.array([5,4,3,2,1])
b = np.array([1,2,3,4,5])

c =np.reshape(b,(1,5,1))
print(c.shape)
print(b.shape)
print(np.reshape(a,(1,5)))
print(np.reshape(b,(1,5)))


print(l2_dist(a.T,b.T))
print(l2_dist(a,b))
print(l2_dist(np.reshape(a,(1,5)),np.reshape(b,(1,5,1))))
print(l2_dist(np.reshape(a,(1,5)),np.reshape(b,(1,5))))

In [4]:
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [18]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]
